services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3001
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
